### ISSUE TITLE
abstract interface class IWidgetModel does not let writing mixin ON it

### ISSUE THREAD

**Issue by khamidjon** [Elementary-team/flutter-elementary#112]
hi Mikhail, I hope you're doing well.

We have been using 1.5.0 version of this package since it was published. During this time, we were used to writing mixins to re-use some methods on WidgetModels. If the methods were used on screen itself, we made them abstract and visible to screen like this:

```
 mixin IReusableWidgetModelMixin on IWidgetModel { // now with >3 versions, we're forced to remove "on IWidgetModel"
     void reusableMethod();
 }

mixin ReusableWidgetModelMixin on WidgetModel implements IReusableWidgetModelMixin {
      @override
      void reusableMethod() {
            // implementation
     }
}


abstract class ISomeScreen extends IWidgetModel with IReusableWidgetModelMixin {} 

class SomeScreen extends WidgetModel with ReusableWidgetModelMixin {}
```

since IWidgetModel is now abstract interface class, we are forced to implement it and we need to remove "on IWidgetModel" from our abstract mixins which is not desirable, because they will be available to use everywhere.

could you help us with this? I have idea to fork the package and make IWidgetModel back to abstract class, would it be correct?

**Comment by MbIXjkee** [comment]
Hi Khamidjon.

On that version, there were no proper interface classes in Dart. So that is the reason IWidgetModel was just an abstract class, but by the semantic meaning, it was always just a proper contract and should not contain implementation. But it looks like you don't need to add mixin on top of the interface. You can instead of it compose interfaces

abstract interface class IReusableSmth {
   void reusableMethod();
}

mixin ReusableWidgetModelMixin on WidgetModel implements IReusableSmth {
      @override
      void reusableMethod() {
            // implementation
     }
}

abstract interface class IExampleWidgetModel implements IWidgetModel, IReusableSmth {}

And then apply IExampleWidgetModel on your implementation of IExampleWidgetModel

**Comment by khamidjon** [comment]
Yeah got you, thank you for the direction. We will convert "interface mixins" into normal interfaces.

By the way, thank you for the package as well, have a great day!
